name: JoinMessages
version: '${project.version}'
main: me.rimon.joinmessages.JoinMessages
api-version: '1.20'
commands:
  togglejoinmessage:
    description: Toggle your welcome messages
    usage: /togglejoinmessage
